name: Daily Commit Workflow

# Schedule the workflow to run daily at a specific time
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 PM UTC every day

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step with your email in its name
      - name: Add commit with email 23f2002291@ds.study.iitm.ac.in
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Create a new file or modify an existing one
          echo "Daily commit on $(date)" >> daily-commit.txt

          # Stage the changes
          git add daily-commit.txt

          # Commit the changes
          git commit -m "Daily automated commit by GitHub Actions"

          # Push the changes to the repository
          git push origin main
